### ISSUE TITLE
Incompatible with MCPC-Plus

### ISSUE THREAD

**Issue by ChrisLane** [Mumfrey/ClientPermissionsPlugin#1]
This plugin isn't working on my server, I tested with VoxelMap and the Macros mod and neither were blocked (no, I wasn't OP).

I am running MCPC-Plus as my server version (modded bukkit) and so maybe that's the reason. Could you possibly look into making some compatibility for this?

Link to mcpc-plus latest build (at this time): http://ci.md-5.net/job/MCPC-Plus/51/

**Comment by Mumfrey** [comment]
This is a [known issue with MCPC+](https://github.com/MinecraftPortCentral/MCPC-Plus/issues/866) which means that plugin channels (a basic feature of the Minecraft protocol required for this to work) don't work.

Until MCPC+ fixes this issue there is no way to use any mods which require plugin channels to work to talk to Bukkit.

**Comment by ChrisLane** [comment]
Okay, thanks for letting me know.

**Comment by ChrisLane** [comment]
It's fixed!
Seems that this is the only working method now since the colour codes don't work with VoxelMap.
